package com.example.herbai;

import android.content.SharedPreferences;
import android.os.Bundle;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.app.AppCompatDelegate;

import com.google.android.material.materialswitch.MaterialSwitch;

public class PlantDetailActivity extends AppCompatActivity {
    private MaterialSwitch themeSwitch;
    private SharedPreferences sharedPreferences;
    private static final String PREFS_NAME = "theme_prefs";
    private static final String NIGHT_MODE = "night_mode";

    private TextView plantNameTextView;
    private TextView scientificNameTextView;
    private TextView taxonomyTextView;
    private TextView medicinalPropertiesTextView;
    private TextView usesTextView;
    private TextView habitatTextView;
    private TextView chemicalComponentsTextView;
    private TextView dataSourceTextView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Load saved theme preference
        sharedPreferences = getSharedPreferences(PREFS_NAME, MODE_PRIVATE);
        boolean isNightMode = sharedPreferences.getBoolean(NIGHT_MODE, false);
        AppCompatDelegate.setDefaultNightMode(isNightMode ?
                AppCompatDelegate.MODE_NIGHT_YES : AppCompatDelegate.MODE_NIGHT_NO);

        setContentView(R.layout.activity_plant_detail);

        initializeViews();
        setupThemeSwitch();
        displayPlantDetails();
    }

    private void initializeViews() {
        themeSwitch = findViewById(R.id.themeSwitch);
        plantNameTextView = findViewById(R.id.plantNameTextView);
        scientificNameTextView = findViewById(R.id.scientificNameTextView);
        taxonomyTextView = findViewById(R.id.taxonomyTextView);
        medicinalPropertiesTextView = findViewById(R.id.medicinalPropertiesTextView);
        usesTextView = findViewById(R.id.usesTextView);
        habitatTextView = findViewById(R.id.habitatTextView);
        chemicalComponentsTextView = findViewById(R.id.chemicalComponentsTextView);
        dataSourceTextView = findViewById(R.id.dataSourceTextView);
    }

    private void setupThemeSwitch() {
        boolean isNightMode = sharedPreferences.getBoolean(NIGHT_MODE, false);
        themeSwitch.setChecked(isNightMode);

        themeSwitch.setOnCheckedChangeListener((buttonView, isChecked) -> {
            SharedPreferences.Editor editor = sharedPreferences.edit();
            editor.putBoolean(NIGHT_MODE, isChecked);
            editor.apply();

            if (isChecked) {
                AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);
            } else {
                AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);
            }
            recreate();
        });
    }

    private void displayPlantDetails() {
        // Get data from intent
        String plantName = getIntent().getStringExtra("plant_name");
        String scientificName = getIntent().getStringExtra("scientific_name");
        String family = getIntent().getStringExtra("family");
        String kingdom = getIntent().getStringExtra("kingdom");
        String genus = getIntent().getStringExtra("genus");
        String species = getIntent().getStringExtra("species");
        String medicinalProperties = getIntent().getStringExtra("medicinal_properties");
        String uses = getIntent().getStringExtra("uses");
        String habitat = getIntent().getStringExtra("habitat");
        String chemicalComponents = getIntent().getStringExtra("chemical_components");
        boolean autoGenerated = getIntent().getBooleanExtra("auto_generated", false);
        String dataSource = getIntent().getStringExtra("data_source");

        // Display the data
        String displayName = plantName + (autoGenerated ? " 🌐" : "");
        plantNameTextView.setText(displayName);

        scientificNameTextView.setText("Scientific Name: " + (scientificName != null ? scientificName : "Unknown"));

        // Build taxonomy string
        String taxonomy = String.format(
                "Kingdom: %s\nFamily: %s\nGenus: %s\nSpecies: %s",
                kingdom != null ? kingdom : "Plantae",
                family != null ? family : "Unknown Family",
                genus != null ? genus : "Unknown",
                species != null ? species : "Unknown"
        );
        taxonomyTextView.setText(taxonomy);

        medicinalPropertiesTextView.setText(medicinalProperties != null ? medicinalProperties : "Information not available");
        usesTextView.setText(uses != null ? uses : "Uses to be researched");
        habitatTextView.setText(habitat != null ? habitat : "Various environments");
        chemicalComponentsTextView.setText(chemicalComponents != null ? chemicalComponents : "Components under study");

        // Data source information
        String sourceText = "Data Source: " + ("Knowledge Graph");
        if (autoGenerated) {
            sourceText += "\n(Auto-generated from APIs)";
        }
        dataSourceTextView.setText(sourceText);
    }
}